definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    enabled: true
    menu_name: main
    parent: ''
    expanded: false
    weight: -50
  active_theme_behaviors__node_add_article:
    weight: -45
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
